name: Gradle plugin build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - gradle.properties
      - .github/.release-please-manifest.json
      - .github/renovate.json

  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - README.md
      - gradle.properties
      - .github/.release-please-manifest.json
      - .github/renovate.json

jobs:
  call-build:
    uses: GrassMC/.github/workflows/shared-gradle-build.yml@main
