name: Gradle plugin deploy
on:
  push:
    branches: [ main ]

jobs:
  call-release:
    uses: GrassMC/.github/.github/workflows/shared-release.yml@main
    permissions:
      contents: write
      pull-requests: write

  call-publish:
    needs: [ call-release ]
    if: ${{ needs.call-release.outputs.release-created == 'true' }}
    uses: GrassMC/.github/.github/workflows/shared-gradle-publish-tozydev.yml@main
    secrets: inherit
    concurrency:
      cancel-in-progress: true
      group: gradle-plugin-publish
